### ISSUE TITLE
pairtools sort fails

### ISSUE THREAD

**Issue by BeetleMilk** [dovetail-genomics/Micro-C#1]
I am trying to use pairtools sort for my .pairsam file using the following command:
pairtools sort --nproc 16 --tmpdir=/.../temp  parsed.pairsam > sorted.pairsam

I think I gave it sufficient amount of memory and time to run. However, even after 2 days, the sorted.pairsam file did not contain any sorted pairs, only the #chromsize and #samheader columns, etc, ending on:
#columns: readID chrom1 pos1 chrom2 pos2 strand1 strand2 pair_type sam1 sam2

No errors were reported. What could be the issue?

**Comment by michalsakin** [comment]
Hi,

Here are a few questions to try and find what the issue is:
1. Did you used a full path for the temp folder? 
2. Do you see if it's still running? (top/htop command)?
3. Are there any new files in the temp folder, do you see their size and date updating?
4. How large is your fastq file (how many reads) and what resources are you using?

**Comment by BeetleMilk** [comment]
1. Yes.
2. It was terminated on server due to time limit (I gave two days limit).
3. Yes, there have been new files added up until the command was terminated. But still no sorted pairs in the output file.
4. The initial fastq files contained 1.1 billion reads. The resulting alignment file was 1.6 Tb in size. 
The pairtools parse command ran for almost 24 hours on that alignment file, but it was successfully finished.

**Comment by michalsakin** [comment]
See our comment from our Omni-C page (running time should be the same):
"The full process including installation, aligning and filtering, library QC, generating contact map and identifying chromatin structures can be completed in less than 48hr compute time for a 800M reads human data set on an Ubuntu 18.04 machine with a 2T volume, 16 CPUs and 64GiB."

I hope this helps. If you think you have enough storage space and memory, consider giving it a bit longer time (although I would expect 2 days to be more than needed). I wanted also to suggest opening an issue on pairtools repository, but I see you already did so :) 
On pairtools issues I saw a single mentioning of pairtools sort not parallelizing https://github.com/open2c/pairtools/issues/72 any chance you are experiencing a similar issue?

**Comment by BeetleMilk** [comment]
Problem solved by giving the command more time to run (> 4 days).
