### ISSUE TITLE
Could you please tell me the exact meaning of '-5SP'?

### ISSUE THREAD

**Issue by hanshanmengqi** [dovetail-genomics/Micro-C#6]
@torchij Hello,

I'm new to the BWA software, and I do not understand the parameter '-5SP' in bwa mem.
Could you please explain it to me?

Thanks!
Han

**Comment by mlkhawand** [comment]
Hi Han,

Attached is a description of the flags.

Best,
Myriam
![Screenshot 2024-03-22 at 1 28 16 PM](https://github.com/dovetail-genomics/Micro-C/assets/59671588/a977d934-1970-4780-98f5-5b9e6c0bf2fd)
