### ISSUE TITLE
Preseq on QC sequencing

### ISSUE THREAD

**Issue by doanthaodinh** [dovetail-genomics/Micro-C#8]
Hi, I am setting up the Micro-C analysis pipeline using the available example files, and I am somewhat confused on the use of preseq to calculate library complexity from shallow QC sequencing. The example tutorial script used the output of pairtools dedup as input, as follow:

bwa mem -5SP -T0 -t16 hg38.fasta MicroC_2M_R1.fastq MicroC_2M_R2.fastq -o aligned.sam
pairtools parse --min-mapq 40 --walks-policy 5unique --max-inter-align-gap 30 --nproc-in 8 --nproc-out 8 --chroms-path hg38.genome aligned.sam >  parsed.pairsam
pairtools dedup --nproc-in 8 --nproc-out 8 --mark-dups --output-stats stats.txt --output _dedup.pairsam_ sorted.pairsam
pairtools split --nproc-in 8 --nproc-out 8 --output-pairs mapped.pairs --output-sam **unsorted.bam** _dedup.pairsam_
samtools sort -@16 -T /home/ubuntu/ebs/temp/temp.bam -o **_mapped.PT.bam_ unsorted.bam**
preseq lc_extrap -bam -pe -extrap 2.1e9 -step 1e8 -seg_len 1000000000 -output out.preseq **_mapped.PT.bam_**
which yields
TOTAL_READS     EXPECTED_DISTINCT	LOWER_0.95CI    UPPER_0.95CI
0	0	0	0
100000000.0     77505593.6	75169210.2	78187273.2
200000000.0     127407958.8     117388222.6     129344470.0
300000000.0     162265082.3     143079770.9     165448919.5

However, the tutorial notes that the input BAM file should be a version prior to duplication removal. Given this is the case, I have also attempted to use preseq on pre-deduplicated BAM, as follow:
bwa mem -5SP -T0 -t16 hg38.fasta MicroC_2M_R1.fastq MicroC_2M_R2.fastq -o **aligned.sam**
samtools sort -@16 -T /home/ubuntu/temp.bam -o **_sorted2.bam_** **aligned.sam**
preseq lc_extrap -bam -pe -extrap 2.1e9 -step 1e8 -seg_len 1000000000 -output out.preseq **_sorted2.bam_**
which yields 
OTAL_READS     EXPECTED_DISTINCT	LOWER_0.95CI    UPPER_0.95CI
0	0	0	0
100000000.0     78939225.0	77213797.4	79566978.4
200000000.0     131473459.7     122999629.0     133119540.1
300000000.0     168999736.6     152295036.2     171622710.0

How is it possible that pre-deduplicated data yields more expected distinct reads than deduplicated? And in the future, which of the BAM should be used as input for preseq?

**Comment by mlkhawand** [comment]
Thank you for reaching out. The duplicates in the mapped.PT.bam are only marked, but not removed. You can use the mapped.PT.bam file for pre-seq.

**Comment by mlkhawand** [comment]
@torchij Hi Jon, this is an inquiry we have received before. I think the current verbiage in the RTD "Please note that the input bam file should be a version prior to dups removal" is confusing to customers. Is it possible to please change the verbiage and point customers to the right input file to use for preseq? We have the same note for preseq across all the RTDs. Thanks!
